const RADIUS = 6378137;
const FLATTENING_DENOM = 298.257223563;
const FLATTENING = 1 / FLATTENING_DENOM;
const POLAR_RADIUS = RADIUS * (1 - FLATTENING);

module.exports = {
  RADIUS,
  FLATTENING_DENOM,
  FLATTENING,
  POLAR_RADIUS
};
